baseURL = 'https://Brown-University-Library.github.io/clydedavenport/'
locale = 'en-us'
title = 'Clyde Davenport'
theme = 'brown-hugo-starter'

sectionPagesMenu = 'main'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
		footnote = true
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'